name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y pkg-config libcairo2-dev libpangocairo-1.0-0 libpango-1.0-0 libpango1.0-dev libgdk-pixbuf2.0-dev libx11-dev
    - name: make
      run: make
    - name: make lint
      run: make lint
